project:
  type: website
  output-dir: docs

website:
  title: "Chris Chamberlin"
  page-footer: 
    left: "Test"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    page-layout: full

editor: visual

